FROM toposoid/toposoid-scala-lib:0.5

WORKDIR /app
ARG TARGET_BRANCH
ARG JAVA_OPT_XMX
ENV DEPLOYMENT=local
ENV _JAVA_OPTIONS="-Xms256m -Xmx"${JAVA_OPT_XMX}

RUN git clone https://github.com/toposoid/scala-data-accessor-neo4j-web.git \
&& cd scala-data-accessor-neo4j-web \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH}

